name: Release Docker Image

on:
  push:
    tags:
      - v**

jobs:
  Release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Login to docker registry
        uses: docker/login-action@v2
        with:
          registry: ${{ secrets.DOCKER_IMAGE_REGISTRY }}
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Get Docker Image Url
        id: image
        env:
          URL: ${{ secrets.DOCKER_IMAGE_REGISTRY }}${{ secrets.DOCKER_IMAGE_PATH }}
        run: |
          echo LATEST=${URL}:latest >> $GITHUB_OUTPUT${{ steps.image.outputs.VERSION }},${{ steps.image.outputs.LATEST }}
          echo VERSION=${URL}:${GITHUB_REF/refs\/tags\//} >> $GITHUB_OUTPUT

      - name: Build the Docker image
        run: |
          docker build . --file dockerfile \
          --tag ${{ steps.image.outputs.VERSION }} \
          --tag ${{ steps.image.outputs.LATEST }}

      - name: Push
        run: |
          docker push ${{ steps.image.outputs.VERSION }}
          docker push ${{ steps.image.outputs.LATEST }}